name: "Komga"
version: "1.26.1"
slug: "komga"
description: >
  Komga is a media server for your comics, mangas, BDs, magazines and eBooks.
  Example:
  Opens the web interface: http://[HOST]:[PORT:25600]/
  Normal link: http://homeassistant.local:25600/
url: "https://komga.org/docs/introduction"
webui: "http://[HOST]:[PORT:25600]/" 
arch:
  - amd64
  - aarch64
  - armhf
  - i386
  - armv7
ports:
  25600/tcp: 25600
map:
  - type: addon_config
    read_only: false
  - type: media
    read_only: false
  - type: share
    read_only: false
image: "ghcr.io/gotson/komga"
